# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kusage < Formula
  desc "Rank Kubernetes pods/containers by CPU/memory usage (usage ÷ limit)."
  homepage "https://github.com/mchmarny/kusage"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/kusage/releases/download/v0.2.3/kusage_v0.2.3_darwin_amd64.tar.gz"
      sha256 "1bb091451f8c7a7cd06782e7aa9882586f21f3170bfb9025fbf5e487ac90deb3"

      def install
        bin.install "kusage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mchmarny/kusage/releases/download/v0.2.3/kusage_v0.2.3_darwin_arm64.tar.gz"
      sha256 "9e3e4f6aff79f55d23514fde4fd7d3a6fcb56aedd2c5b6dd585971c0f788b12e"

      def install
        bin.install "kusage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/kusage/releases/download/v0.2.3/kusage_v0.2.3_linux_amd64.tar.gz"
      sha256 "a15b902bb0102484cde7170e538da548e9235bde4e40ede0b0636a97e80e4e98"
      def install
        bin.install "kusage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/kusage/releases/download/v0.2.3/kusage_v0.2.3_linux_arm64.tar.gz"
      sha256 "ff7c25285382db28322ac70a0f830435b0abdcc121fcfc59d755f2652513d6c0"
      def install
        bin.install "kusage"
      end
    end
  end

  test do
    system "#{bin}/kusage --help"
  end
end
