# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kusage < Formula
  desc "Rank Kubernetes pods/containers by CPU/memory usage (usage ÷ limit)."
  homepage "https://github.com/mchmarny/kusage"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/kusage/releases/download/v0.1.3/kusage_v0.1.3_darwin_amd64.tar.gz"
      sha256 "d3968d729be924d5a3fc3872594351e0ce48fa23016abeb838d79b8442a59b8c"

      def install
        bin.install "kusage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mchmarny/kusage/releases/download/v0.1.3/kusage_v0.1.3_darwin_arm64.tar.gz"
      sha256 "afbdb6c3890264373fa447be5b91edad9d18de4f6cb0905386858d7f3e737deb"

      def install
        bin.install "kusage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/kusage/releases/download/v0.1.3/kusage_v0.1.3_linux_amd64.tar.gz"
      sha256 "700f3949137ed379442a48fd6772544ea72174d270b5f65e45bcfe1489760fdf"
      def install
        bin.install "kusage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/kusage/releases/download/v0.1.3/kusage_v0.1.3_linux_arm64.tar.gz"
      sha256 "5d50e1e0885a7492d38555813cecc97be7bf9f69ac322b2683f79170ee6af8db"
      def install
        bin.install "kusage"
      end
    end
  end

  test do
    system "#{bin}/kusage --help"
  end
end
