# This file was generated by GoReleaser. DO NOT EDIT.
cask "kusage" do
  name "kusage"
  desc "Rank Kubernetes pods/containers by CPU/memory usage (usage ÷ limit)."
  homepage ""
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/mchmarny/kusage/releases/download/v#{version}/kusage_v#{version}_darwin_amd64"
      sha256 "402850f55dc6171d082d6dcb8896758eebb3ce9acadf1490a1f1d121f23b744e"
      binary "kusage_v0.0.3_darwin_amd64", target: "kusage"
    end
    on_arm do
      url "https://github.com/mchmarny/kusage/releases/download/v#{version}/kusage_v#{version}_darwin_arm64"
      sha256 "64f359933aed202ea239d4872f6680f0762b35406f3d6ef65bfb49d8694d0a97"
      binary "kusage_v0.0.3_darwin_arm64", target: "kusage"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mchmarny/kusage/releases/download/v#{version}/kusage_v#{version}_linux_amd64"
      sha256 "64ac547e76698e2b587a9b70ceca729d6357028e6089ebd66ac640ae0d77e786"
      binary "kusage_v0.0.3_linux_amd64", target: "kusage"
    end
    on_arm do
      url "https://github.com/mchmarny/kusage/releases/download/v#{version}/kusage_v#{version}_linux_arm64"
      sha256 "f3959b98075083e5d09ea5dfc1486e723015d0d2305f0ce4693262ca6793c0d5"
      binary "kusage_v0.0.3_linux_arm64", target: "kusage"
    end
  end

  # No zap stanza required
end
